# Generated by Django 4.1.7 on 2023-06-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Quantaty',
            new_name='quantity',
        ),
    ]
